#pragma library markers-consts

// Название сервера
#define SERVER_NAME  "markers Role Play"

// Структура подключения к SQL
#define SQL_HOST  "127.0.0.1"
#define SQL_USER  "root"
#define SQL_PASSWORD  ""
#define SQL_DB  "samp"


// Цвета для диалогов и чата
#define C_COLOR_WHITE "{FFFFFF}"
#define C_COLOR_GREY "{AFAFAF}"
#define C_COLOR_RED "{FF0000}"
#define C_COLOR_YELLOW "{FFFF00}"
#define C_COLOR_LIGHTBLUE "{33CCFF}"
#define C_COLOR_LIMEGREEN "{32CD32}"
#define C_COLOR_CORNFLOWERBLUE "{6495ED}"
#define C_COLOR_TOMATO "{FF6347}"
#define C_COLOR_BLUE "{0000FF}"

// Цвета прочие
#define COLOR_WHITE 0xFFFFFFAA
#define COLOR_GREY 0xAFAFAFAA
#define COLOR_RED 0xFF0000AA
#define COLOR_YELLOW 0xFFFF00AA
#define COLOR_LIGHTBLUE 0x33CCFFAA
#define COLOR_TOMATO 0xFF6347AA
#define COLOR_BLUE 0x0000FFAA

// Список ID запрещённого оружия
new deleted_weapons[6] =
{
	39,
	40,
	35,
	36,
	37,
	38
}