#pragma library markers
#define SERVER_NAME = "markers Role Play";

enum SQL_CONNECT_PROPERTIES_STRUCTURE
{
	Host = "localhost",
	Login = 2,
	Password = 4,
	DataBase = "samp"
};

enum COLORS_CHAT
{
	White = "{FFFFFF}",
	Grey = "{AFAFAF}",
	Red = "{FF0000}",
	Yellow = "{FFFF00}",
	LightBlue = "{33CCFF}",
	LimeGreen = "{32CD32}",
	CornflowerBlue = "{6495ED}"
};

enum COLORS
{
	White = 0xFFFFFFAA,
	Grey = 0xAFAFAFAA,
	Red = 0xFF0000AA,
	Yellow = 0xFFFF00AA,
	LightBlue = 0x33CCFFAA
};